### ISSUE TITLE
"Slime on Windows" - Solution for showing the window!

### ISSUE THREAD

**Issue by resttime** [commonqt/commonqt#24]
I was able to get my window to appear by invoking the hide and show functions of QT in some combination.
```cl
(#_show window)
(#_hide window)
(#_show window)
```

![test](https://cloud.githubusercontent.com/assets/2598904/9020835/16e9d5cc-37e9-11e5-9ed3-de366ac0047d.png)

**Comment by stassats** [comment]
That doesn't help here.

**Comment by resttime** [comment]
Did I misunderstand the problem? Let me edit my previous post because I also think I got the combination wrong.

I was looking at the [documentation](https://common-lisp.net/project/commonqt/#known-issues) at the time which said that "Running from Slime under Windows doesn't appear to work" and I also experienced the problem. Doing show-hide trickery was what let my window appear. After doing it once, any subsequent call doesn't require it anymore.

![demo](https://cloud.githubusercontent.com/assets/2598904/9422127/de74f46e-484c-11e5-91c5-7ea93704f8d3.gif)

**Comment by stassats** [comment]
This doesn't solve the problem.

**Comment by resttime** [comment]
Ah sorry, I understand what you mean now. I have only found another superficial work around. Would adding this information to the commonqt documentation be helpful because one can get things running without opening the CL implementation from cmd.exe?

**Comment by stassats** [comment]
I tried the code from the first screenshot, it didn't show the window first, that's why it didn't work for me. I added this to the FAQ.
