### ISSUE TITLE
(qdescribe "QsciScintilla") error caused by QAbstractScrollArea

### ISSUE THREAD

**Issue by jurov** [commonqt/commonqt#27]
On Linux x64, both in SBCL and ECL. Output from SBCL-1.3.0 with qt-libs loaded by quicklisp:
```
* (qt:qdescribe "QsciScintilla")
5504 <86,0,0> is a smoke class

    name: QsciScintilla
    flags: #x5 (VIRTUAL, CONSTRUCTOR)

Superclasses:
    QsciScintillaBase

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1002ADC5A3}>:
  The value NIL is not of type (UNSIGNED-BYTE 4).
0] backtrace

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002ADC5A3}>
0: (QT:FIND-QCLASS "QAbstractScrollArea" T)
1: (QT:LIST-QCLASS-SUPERCLASSES 5568)
2: ((LABELS QT::RECURSE :IN QT::DESCRIBE-QCLASS) 5568 8)
3: ((LABELS QT::RECURSE :IN QT::DESCRIBE-QCLASS) 5504 4)
4: (QT::DESCRIBE-QCLASS 5504 NIL)
5: (QT:QDESCRIBE "QsciScintilla" NIL)
6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QT:QDESCRIBE "QsciScintilla") #<NULL-LEXENV>)
7: (EVAL (QT:QDESCRIBE "QsciScintilla"))
8: (INTERACTIVE-EVAL (QT:QDESCRIBE "QsciScintilla") :EVAL NIL)
9: (SB-IMPL::REPL-FUN NIL)
10: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
11: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {10047B2C7B}>)
12: (SB-IMPL::TOPLEVEL-REPL NIL)
13: (SB-IMPL::TOPLEVEL-INIT)
14: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
15: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

The result of standalone (qt:qdescribe "QAbstractScrollArea") is NIL.

**Comment by Shinmera** [comment]
Looks like you didn't load the smoke modules for QtCore/QtGui yet, which leads to the problem of it being unable to find the QAbstractScrollArea class. If you ensure that those two modules are loaded first, the problem should cease.

Another tip: if you use Qtools, you should use the ASDF wrapper classes it provides (in this case, `:qsci`), as those ensure that all depedencies are properly resolved and issues like this cannot happen.

**Comment by jurov** [comment]
Thanks, (qt:ensure-smoke :qtgui) resolved the issue. I don't use Qtools, I prefer to keep clear correspondence with C++.

**Comment by stassats** [comment]
Or just do make-qapplication, which would (ensure-smoke :qtcore) and (ensure-smoke :qtgui)
