### ISSUE TITLE
Mismatched types in :QT-SUPERCLASS messages

### ISSUE THREAD

**Issue by phoe** [commonqt/commonqt#31]
```
(defclass palette (widget) ()
  (:qt-superclass 'qwidget)
  (:metaclass widget-class))
 
'QWIDGET fell through ETYPECASE expression.
Wanted one of (FIXNUM STRING SYMBOL QOBJECT).
   [Condition of type SB-KERNEL:CASE-FAILURE]
```

```  
(defclass palette (widget) ()
  (:qt-superclass qwidget)
  (:metaclass widget-class))
 
The value of QT::NAME is QWIDGET, which is not of type STRING.
   [Condition of type SIMPLE-TYPE-ERROR]
```

The messages `The value of QT::NAME is QWIDGET, which is not of type STRING.` and `Wanted one of (FIXNUM STRING SYMBOL QOBJECT).` contradict each other. It's a minor annoyance, but might want to fix it one day.

**Comment by stassats** [comment]
I'm not sure what
```
(defclass palette (widget) ()
  (:qt-superclass 'qwidget)
  (:metaclass widget-class))
```
is supposed to be, but
```
(defclass palette () ()
  (:qt-superclass 'qwidget)
  (:metaclass qt-class))
```
gives the same errors with either qwidget or 'qwidget.

**Comment by phoe** [comment]
`WIDGET` is `QTOOLS:WIDGET` class.

Now that I look at it, I guess that I screwed something up while writing my Qtools CLOS definitions. I will close this issue because it makes no sense.
