### ISSUE TITLE
Signal name is corrupted - first letter is chopped off

### ISSUE THREAD

**Issue by phoe** [commonqt/commonqt#35]
We have the following code:

```
(defclass test-label (widget) ()
  (:qt-superclass "QLabel")
  (:metaclass widget-class)
  (:signals ("requestChangeText()"))
  (:slots ("changeText()"
           (lambda (this)
             (#_setText this "Boo!")))))

(defun test ()
  (with-main-window (this (make-instance 'test-label))
    (#_setText this "Peek a...")
    (connect this "requestChangeText()" this "changeText()")
    (#_QTimer::singleShot 2000 this "requestChangeText()")))
```

Evaluating `(test)` shows the following in the `*inferior-lisp*` buffer:
```
Object::connect: No such signal FOX5/QT::TEST-LABEL::equestChangeText()
```

But if we modify TEST's last line:
```
(defun test ()
  (with-main-window (this (make-instance 'test-label))
    (#_setText this "Peek a...")
    (connect this "requestChangeText()" this "changeText()")
    (#_QTimer::singleShot 2000 this "rrequestChangeText()")))
```

The code works as expected - after two seconds, the text on the label is changed.

The bug: the signal name mentioned in the `*inferior-lisp*` buffer is `FOX5/QT::TEST-LABEL::equestChangeText()` and is missing the initial `r` letter. Adding a single letter to the signal name, `"rrequestChangeText()"` in this example, makes the code work. Therefore I suspect that something is chopping off that initial letter of the signal name.

**Comment by stassats** [comment]
Cause you didn't use (qsignal "requestChangeText()")

**Comment by phoe** [comment]
Thanks! Works now.

What if I didn't want to do it via the signal but use the slot directly instead? The following code:

```
(defun test ()
  (qt:with-main-window (this (make-instance 'test-label))
    (#_setText this "Peek a...")
    (connect this "requestChangeText()" this "changeText()")
    (#_QTimer::singleShot 2000 this "changeText()")))
```
seems to follow the convention from the documentation as used in https://common-lisp.net/project/commonqt/#id106138 `(connect sender "signal()" receiver "slot()")` but still fails with
```
Object::connect: Use the SLOT or SIGNAL macro to connect FOX5/QT::TEST-LABEL::changeText()
```

**Comment by phoe** [comment]
...oooh, `#'QSLOT`. nifty.
