### ISSUE TITLE
use (:qt-superclass "QGraphicsEllipseItem") error

### ISSUE THREAD

**Issue by jamesbake** [commonqt/commonqt#36]
i have a question abort use QGraphicsEllipseItem, this is my code
```
(defclass node-connector ()
  ()
  (:metaclass qt-class)
  (:qt-superclass "QGraphicsEllipseItem")
  )

(defmethod initialize-instance :after ((instance node-connector) &key parent)
  (if parent
      (new instance parent)
      (new instance))
  )

```
when i use (make-instance 'node-connector)  it goes wrong aboat this:
``
The value
  NIL
is not of type
  (SIGNED-BYTE 16)
when binding SB-ALIEN::VALUE
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {25007EE1}>)

Backtrace:
  0: (QT::SW_MAKE_DYNAMIC_BINDING #.(SB-SYS:INT-SAP #X00A4E880) #.(SB-SYS:INT-SAP #X05600D00) NIL NIL #.(SB-SYS:INT-SAP #X221106A8) #.(SB-SYS:INT-SAP #X221106F8) #.(SB-SYS:INT-SAP #X22110720))
  1: (QT::SET-CLASS-BINDING #<QT:QT-CLASS QT-TEST:NODE-CONNECTOR>)
  2: (QT::ENSURE-QT-CLASS-CACHES #<QT:QT-CLASS QT-TEST:NODE-CONNECTOR>)
  3: ((:METHOD INITIALIZE-INSTANCE (QT:DYNAMIC-OBJECT)) #<QT-TEST:NODE-CONNECTOR uninitialized>) [fast-method]
  4: ((SB-PCL::EMF INITIALIZE-INSTANCE) #<unused argument> #<unused argument> #<QT-TEST:NODE-CONNECTOR uninitialized>)
  5: ((:METHOD INITIALIZE-INSTANCE :AROUND (QT:DYNAMIC-OBJECT)) #<QT-TEST:NODE-CONNECTOR uninitialized>) [fast-method]
  6: (SB-PCL::FAST-MAKE-INSTANCE #<unavailable argument> #<unavailable &MORE argument>)
  7: ((:METHOD INITIALIZE-INSTANCE :AFTER (QT-TEST:GAME-BOARD)) #<QT-TEST:GAME-BOARD QWidget 0x00B1F160> :PARENT NIL) [fast-method]
  8: ((SB-PCL::EMF INITIALIZE-INSTANCE) #<unused argument> #<unused argument> #<QT-TEST:GAME-BOARD QWidget 0x00B1F160>)
  9: ((:METHOD INITIALIZE-INSTANCE :AROUND (QT:DYNAMIC-OBJECT)) #<QT-TEST:GAME-BOARD QWidget 0x00B1F160>) [fast-method]
 10: (SB-PCL::FAST-MAKE-INSTANCE #<unavailable argument> #<unavailable &MORE argument>)
 11: (QT-TEST:MAIN)
 12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QT-TEST:MAIN) #<NULL-LEXENV>)
 13: (EVAL (QT-TEST:MAIN))
 --more--

``

how can i resolve this problem, thank you

**Comment by stassats** [comment]
It's not inheriting from QObject, it can't be subclassed.

**Comment by jamesbake** [comment]
thanks alot for all your answers
